# Generated by Django 4.1.7 on 2023-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_navigation_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='brochure',
            field=models.FileField(default=None, null=True, upload_to='brochure/'),
        ),
    ]
