# Generated by Django 4.1.7 on 2023-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_globalsettings_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='back_image',
            field=models.ImageField(null=True, upload_to='admin/'),
        ),
    ]
